import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import prisma from "@/utils/prisma";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export  default async function RootLayout({ children }) {
// const cookieStore = await cookies()
// const sessionId = cookieStore.get("session")?.value
// if(!sessionId) {
//   redirect("/login")
// }

// const session = await prisma.session.findUnique({
//   where : {
//     id : sessionId
//   },
//   select : {
//     id : true
//   }

// })

// if(!session) {
//   redirect("/login")
// }


  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
